- hosts: inetRouter
  become: true
  tasks:
  - name: install iptables
    yum:
      name:
      - iptables
      - iptables-services
      state: present
      update_cache: true

  - name: copy iptables config
    template:
      src: iptables
      dest: /etc/sysconfig/iptables
      owner: root
      group: root
      mode: 0600

  - name: start and enable iptables service
    service:
      name: iptables
      state: restarted
      enabled: true

- hosts: inetRouter, centralRouter
  become: true
  tasks:
  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

- hosts: centralRouter
  become: true
  tasks:
  - name: Set DEFROUTE
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: '.*DEFROUTE.*'
      line: 'DEFROUTE=no'
      state: present  
  - name: add default gateway for centralRouter
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.255.1

  - name: restart network
    systemd:
      name: network
      enabled: yes
      state: restarted  

  - name: set up route on centralRouter eth1
    template:
      src: centralRouter_route_eth1.j2
      dest: /etc/sysconfig/network-scripts/route-eth1
      owner: root
      group: root
      mode: 0644

  - name: set up route on centralRouter eth3
    template:
      src: centralRouter_route_eth3.j2
      dest: /etc/sysconfig/network-scripts/route-eth3
      owner: root
      group: root
      mode: 0644
      
  - name: set up route on centralRouter eth5
    template:
      src: centralRouter_route_eth5.j2
      dest: /etc/sysconfig/network-scripts/route-eth5
      owner: root
      group: root
      mode: 0644

  - name: set up route on centralRouter eth6
    template:
      src: centralRouter_route_eth6.j2
      dest: /etc/sysconfig/network-scripts/route-eth6
      owner: root
      group: root
      mode: 0644

  - name: set up route on centralRouter eth2
    template:
      src: centralRouter_route_eth2.j2
      dest: /etc/sysconfig/network-scripts/route-eth2
      owner: root
      group: root
      mode: 0644

- hosts: inetRouter
  become: true
  tasks:
  - name: set up route on inetRouter eth1
    template:
      src: inetRouter_route_eth1.j2
      dest: /etc/sysconfig/network-scripts/route-eth1
      owner: root
      group: root
      mode: 0644
      
- hosts: testClient1 
  become: true
  tasks:
  - name: set up route on testClient1 
    template:
      src: netplantestClient1
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
      
- hosts: testClient2
  become: true
  tasks:
  - name: set up route on testClient2 
    template:
      src: netplantestClient2
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
      
- hosts: testServer1 
  become: true
  tasks:
  - name: set up route on testServer1 
    template:
      src: netplantestServer1
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644

- hosts: testServer2 
  become: true
  tasks:
  - name: set up route on testServer2 
    template:
      src: netplantestServer2
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
      
  
- hosts: all
  become: true
  tasks:
  - name: reboot
    reboot:
      reboot_timeout: 3600
